#!/bin/sh

# runs when a DM logs you into a graphical session.

xrandr --dpi 96
setbg &

# use Xresources colors/settings on startup

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!

autostart="xcompmgr dunst unclutter pipewire remapd"

# uncoment this when you feel your WM is broing
# autostart="picom dunst unclutter pipewire remapd"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
export XCURSOR_THEME=Breeze
export XCURSOR_SIZE=24
